chore: support intersection type in cdk unit test (#972)
Recent versions of aws-cdk-lib (2.234.0+) started using intersection
types:
[Reference](https://github.com/aws/aws-cdk/commit/3e5e3279073183d637e395f501d7d76cd4b33fde);

Due to this, the upgrade dependency PR started failing with:
```
 FAIL test/real-cdk.test.ts
  ● with aws-cdk-lib › generate example for doubly nested type

    Error loading assembly from file node_modules/aws-cdk-lib/.jsii:
    Error: This jsii tool cannot load the given assembly; using unsupported feature(s): intersection-types (supported features: )
```

Add intersection types as a supported feature to this test to fix the
issue.

---------

Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Leon Michalski <leonmk@amazon.de>