fix: generated examples fail when scope is not of type `Construct` (#262)
In the generated fixture, `this` is of type construct:

```ts
import { Construct } from "constructs";
class MyConstruct extends Construct {
constructor(scope: Construct, id: string) {
super(scope, id);
/// here
} }
```

Therefore we can only supply `this` when the type is the same. Notably, the generated examples fail when the type is an App:

```bash
@aws-cdk.app-staging-synthesizer-alpha.DefaultStagingStack-example.ts:20:83 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'App'.

const defaultStagingStack = new app_staging_synthesizer_alpha.DefaultStagingStack(this, 'MyDefaultStagingStack', {
```